 NUMPY


why numpy?
numpy is a multidimentional array, which can be used to sort all sorts of data 1D-array,2D array, 3D array etc

In [2]:
import numpy as np

The basics

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
b=np.array([[1.0,2.0,3.0],[5.0,6.0,7.0]])
print(b)

[[1. 2. 3.]
 [5. 6. 7.]]


In [8]:
#Get dimesion
a.shape

(4,)

In [9]:
b.shape

(2, 3)

In [10]:
#get type
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [12]:
#get size
a.itemsize

4

In [13]:
b.itemsize

8

In [17]:
#Get total size
a.size
a.nbytes

16

In [18]:
b.size 
b.nbytes #b.size*b.itemsize

48

Accessing/ Changing specific elemeents, rows,columns,etc

In [19]:
a=np.array([[1,2,3,4,5,6],[8,9,5,4,3,3]])
print(a)


[[1 2 3 4 5 6]
 [8 9 5 4 3 3]]


In [29]:
#Get the specific element [r,c]
print(a[0,1]) 

2


In [24]:
a[1,-3]

4

In [25]:
#Get a specific row

In [34]:
a[0, :]
#a[1,:]

array([1, 2, 3, 4, 5, 6])

In [31]:
b[0,:]

array([1., 2., 3.])

In [35]:
#get a specific column
a[:,2]

array([3, 5])

In [36]:
b[:,1]

array([2., 6.])

In [37]:
#getting a little more fancy [startindex:endindex:stepsize]

In [39]:
c=np.array([[1,2,3,3,4,5,6,7,8,9],[2,3,4,5,7,8,6,5,4,3]])
print(c)

[[1 2 3 3 4 5 6 7 8 9]
 [2 3 4 5 7 8 6 5 4 3]]


In [40]:
c[0,2:6:1]  #here 0 is row specification

array([3, 3, 4, 5])

In [41]:
c[1,2:6:1]

array([4, 5, 7, 8])

In [42]:
#changing the elements in the array

In [43]:
c[1,5]=55
print(c)

c[:,2]=5
print(a)

[[ 1  2  3  3  4  5  6  7  8  9]
 [ 2  3  4  5  7 55  6  5  4  3]]


In [46]:
c[:,2]=99
print(c)

[[ 1  2 99  3  4  5  6  7  8  9]
 [ 2  3 99  5  7 55  6  5  4  3]]


In [47]:
c[1,5]=200
c[:,2]=[1,2]
print(c)

[[  1   2   1   3   4   5   6   7   8   9]
 [  2   3   2   5   7 200   6   5   4   3]]


3D examples

In [49]:
d=np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print(d)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [50]:
#get a specific element(work oustside in)
d[0,1,1]

4

In [51]:
d[:,1,:]

array([[3, 4],
       [8, 9]])

In [52]:
d[:,0,:]

array([[1, 2],
       [6, 7]])

In [54]:
#replace
d[:,1,::]=[[9,9],[6,6]]
print(d)

[[[1 2]
  [9 9]]

 [[6 7]
  [6 6]]]


In [56]:
#Initilizing Different type of Arrays

In [57]:
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [67]:
np.ones((2,2),dtype='int32')

array([[1, 1],
       [1, 1]])

In [69]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [71]:
#Any other numeber (full_like)
np.full(c.shape,4)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [72]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [77]:
#Random decimal numbers
np.random.rand(2,3,3)

array([[[0.43797422, 0.33303894, 0.97744853],
        [0.7632448 , 0.7066426 , 0.46518539],
        [0.13844252, 0.96918824, 0.62369087]],

       [[0.47164083, 0.38473312, 0.82841019],
        [0.57198359, 0.27538472, 0.06735207],
        [0.35805355, 0.2218006 , 0.34026508]]])

In [78]:
np.random.random_sample(a.shape)

array([[0.17822078, 0.82587072, 0.88722458, 0.24027883, 0.54439027,
        0.22981817],
       [0.32095492, 0.79061399, 0.43930162, 0.77474088, 0.85187786,
        0.68471593]])

In [81]:
#Random integer values
np.random.randint(1,6,size=(3,3))

array([[1, 4, 2],
       [2, 2, 1],
       [5, 5, 5]])

In [82]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
#Repeat an array 
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [90]:
#EXAMPLE 
output=np.ones((5,5),dtype='int32')
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [97]:
z=np.zeros((3,3),dtype='int32')
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [99]:
z[1,1]=9
print(z)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [100]:
output[1:4,1:4]=z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [101]:
 ################## Be carefull when copying arrays#################

In [104]:
a=np.array([1,3,4,5])
b=a
b[0]=200
print(b)

[200   3   4   5]


In [105]:
print(a) #as we can see that the same change as been made to a also soo need to be very care full while copying

[200   3   4   5]


In [107]:
#we can prevent this by using copy() function
a=np.array([1,3,4,5])
b=a.copy()
b[0]=200
print(b)
print(a)

[200   3   4   5]
[1 3 4 5]


#MATHEMATICS

In [108]:
a=np.array([1,3,4,5,6])
print(a)

[1 3 4 5 6]


In [109]:
a+2

array([3, 5, 6, 7, 8])

In [110]:
a-2

array([-1,  1,  2,  3,  4])

In [111]:
a*2

array([ 2,  6,  8, 10, 12])

In [112]:
a/2


array([0.5, 1.5, 2. , 2.5, 3. ])

In [113]:
b=np.array([6,7,8,9,3])
a+b


array([ 7, 10, 12, 14,  9])

In [114]:
# Take sin or cos
np.sin(a)

array([ 0.84147098,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [115]:
#######Linear algebra######

In [119]:
c=np.ones((2,3))
print(c)
d=np.full((3,4),3)
print(d)
np.matmul(c,d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


array([[9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [120]:
######### Statistics###############
stat=np.array([55,6,7,4])
print(stat)

[55  6  7  4]


In [122]:
np.min(stat)
#np.max(stat)

4

In [123]:
np.max(stat)

55

In [124]:
np.sum(stat)

72

Reorganizing arrays

In [130]:
before=np.array([3,4,5,6])
print(before)

[3 4 5 6]


In [131]:
after=before.reshape((2,2))
print(after)

[[3 4]
 [5 6]]


In [135]:
#Vertically stacking of array
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v2,v1,v2])

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
np.hstack([v2,v1])

array([5, 6, 7, 8, 1, 2, 3, 4])

Load data from file

In [139]:
filedata=np.genfromtxt('data.txt',delimiter=',')
print(filedata)


[ 1.  2.  3.  4.  5.  6.  7.  6.  7. 78.  9.  0.  7.  5.  4.]


In [140]:
filedata.astype('int32')

array([ 1,  2,  3,  4,  5,  6,  7,  6,  7, 78,  9,  0,  7,  5,  4])

Boolean masking and advanced indexing

In [141]:
filedata >6

array([False, False, False, False, False, False,  True, False,  True,
        True,  True, False,  True, False, False])